/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package practica13;

import java.awt.event.MouseMotionListener;
import java.awt.image.BufferedImage;
import java.util.ArrayList;
import sm.gms.eventos.LienzoListener;
import sm.gms.eventos.VentanaInternaEvent;
import sm.gms.eventos.VentanaInternaListener;

/**
 *
 * @author Gloria Méndez Sánchez
 */
public class VentanaInternaImagen extends javax.swing.JInternalFrame {

    //
    ArrayList<VentanaInternaListener> ventanaInternaEventListeners = new ArrayList();
    //
    int valorScrollVertical = 0;
    //
    int valorScrollHorizontal = 0;

    /**
     * Creates new form VentanaInterna
     * @param img Imagen que se visualiza en el lienzo
     */
    public VentanaInternaImagen(BufferedImage img) {
        initComponents();
        // Asigna el tamaño de la ventana
        setSize(400, 300);
        valoresScroll();
        lienzo2D.setImagen(img);
        notifyVentanaInternaChange(new VentanaInternaEvent(this));
    }

    /**
     * @return variable lienzo de la clase
     */
    public sm.gms.iu.Lienzo2D getLienzo() {
        return this.lienzo2D;
    }

    public void addVentanaInternaListener(VentanaInternaListener listener) {
        if (listener != null) {
            this.ventanaInternaEventListeners.add(listener);
        }
    }

    private void notifyVentanaInternaChange(VentanaInternaEvent evt) {
        if (!ventanaInternaEventListeners.isEmpty()) {
            for (VentanaInternaListener listener : ventanaInternaEventListeners) {
                listener.ventanaInternaChange(evt);
            }
        }
    }

    public void addLienzoListener(LienzoListener listener) {
        if (lienzo2D != null)
            this.lienzo2D.addLienzoListener(listener);
    }
    
    public void addRatonListener(MouseMotionListener listener) {
        if (lienzo2D != null)
            this.lienzo2D.addMouseMotionListener(listener);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lienzo2D = new sm.gms.iu.Lienzo2D();
        deslizadorVertical = new javax.swing.JScrollBar();
        deslizadorHorizontal = new javax.swing.JScrollBar();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setMinimumSize(new java.awt.Dimension(100, 80));
        setPreferredSize(new java.awt.Dimension(100, 80));
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentMoved(java.awt.event.ComponentEvent evt) {
                formComponentMoved(evt);
            }
            public void componentResized(java.awt.event.ComponentEvent evt) {
                formComponentResized(evt);
            }
        });

        lienzo2D.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lienzo2DMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout lienzo2DLayout = new javax.swing.GroupLayout(lienzo2D);
        lienzo2D.setLayout(lienzo2DLayout);
        lienzo2DLayout.setHorizontalGroup(
            lienzo2DLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 731, Short.MAX_VALUE)
        );
        lienzo2DLayout.setVerticalGroup(
            lienzo2DLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 343, Short.MAX_VALUE)
        );

        getContentPane().add(lienzo2D, java.awt.BorderLayout.CENTER);

        deslizadorVertical.addAdjustmentListener(new java.awt.event.AdjustmentListener() {
            public void adjustmentValueChanged(java.awt.event.AdjustmentEvent evt) {
                deslizadorVerticalAdjustmentValueChanged(evt);
            }
        });
        getContentPane().add(deslizadorVertical, java.awt.BorderLayout.LINE_END);

        deslizadorHorizontal.setOrientation(javax.swing.JScrollBar.HORIZONTAL);
        deslizadorHorizontal.addAdjustmentListener(new java.awt.event.AdjustmentListener() {
            public void adjustmentValueChanged(java.awt.event.AdjustmentEvent evt) {
                deslizadorHorizontalAdjustmentValueChanged(evt);
            }
        });
        getContentPane().add(deslizadorHorizontal, java.awt.BorderLayout.PAGE_END);
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentMoved(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentMoved
        this.notifyVentanaInternaChange(new VentanaInternaEvent(this));
    }//GEN-LAST:event_formComponentMoved

    private void deslizadorHorizontalAdjustmentValueChanged(java.awt.event.AdjustmentEvent evt) {//GEN-FIRST:event_deslizadorHorizontalAdjustmentValueChanged
        this.lienzo2D.setPosX(-this.deslizadorHorizontal.getValue());
        this.lienzo2D.repaint();
    }//GEN-LAST:event_deslizadorHorizontalAdjustmentValueChanged

    private void deslizadorVerticalAdjustmentValueChanged(java.awt.event.AdjustmentEvent evt) {//GEN-FIRST:event_deslizadorVerticalAdjustmentValueChanged
        this.lienzo2D.setPosY(-this.deslizadorVertical.getValue());
        this.lienzo2D.repaint();
    }//GEN-LAST:event_deslizadorVerticalAdjustmentValueChanged

    private void formComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentResized
        this.valoresScroll();
        this.deslizadorHorizontal.setMaximum(this.valorScrollHorizontal);
        this.deslizadorVertical.setMaximum(this.valorScrollVertical);
    }//GEN-LAST:event_formComponentResized

    private void lienzo2DMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lienzo2DMouseClicked
        this.notifyVentanaInternaChange(new VentanaInternaEvent(this));
    }//GEN-LAST:event_lienzo2DMouseClicked

    private void valoresScroll() {
        if (this.getLienzo().getWidth() < this.getLienzo().getImagen().getWidth())
            this.valorScrollHorizontal = this.getLienzo().getImagen().getWidth() - this.getLienzo().getWidth();
        else
            this.valorScrollHorizontal = 1;
        if (this.getLienzo().getHeight() < this.getLienzo().getImagen().getHeight())
            this.valorScrollVertical = this.getLienzo().getImagen().getHeight() - this.getLienzo().getHeight();
        else
            this.valorScrollVertical = 1;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollBar deslizadorHorizontal;
    private javax.swing.JScrollBar deslizadorVertical;
    private sm.gms.iu.Lienzo2D lienzo2D;
    // End of variables declaration//GEN-END:variables
}
