/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package sm.gms.colores;

import java.awt.Color;

/**
 *
 * @author Gloria
 */
public class VentanaPrincipal extends javax.swing.JPanel {

    /**
     * Creates new form panelColor
     */
    public VentanaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Color colores[] = {Color.BLACK, Color.RED, Color.BLUE, Color.ORANGE, Color.YELLOW, Color.GREEN};
        comboColores = new javax.swing.JComboBox<>(colores);

        setMaximumSize(new java.awt.Dimension(60, 30));
        setMinimumSize(new java.awt.Dimension(60, 30));
        setPreferredSize(new java.awt.Dimension(60, 30));
        setLayout(null);

        comboColores.setMaximumSize(new java.awt.Dimension(60, 30));
        comboColores.setMinimumSize(new java.awt.Dimension(60, 30));
        comboColores.setPreferredSize(new java.awt.Dimension(40, 30));
        comboColores.setRenderer(new ColorCellRender());
        comboColores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboColoresActionPerformed(evt);
            }
        });
        add(comboColores);
        comboColores.setBounds(0, 0, 60, 40);
    }// </editor-fold>//GEN-END:initComponents

    public Color getValue(){
        return (Color)this.comboColores.getItemAt(this.comboColores.getSelectedIndex());
    }
    
    private void comboColoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboColoresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboColoresActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<Color> comboColores;
    // End of variables declaration//GEN-END:variables
}
